name: identity-model\ci

permissions:
  contents: read
  checks: write
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/identity-model-ci.yml
    - identity-model/*
  pull_request:
    paths:
    - .github/workflows/identity-model-ci.yml
    - identity-model/*

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        working-directory: identity-model
        shell: pwsh
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Build
      run: ./build.ps1

    - name: Test report
      id: test-report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Test results
        path: identity-model/test/IdentityModel.Tests/TestResults/Test.trx
        reporter: dotnet-trx
        fail-on-error: true
        fail-on-empty: true

    - name: Install Sectigo CodeSiging CA certificates
      if: contains(matrix.runs-on, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo cp build/SectigoPublicCodeSigningRootCrossAAA.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates

    - name: Sign
      if: github.ref == 'refs/heads/main' && contains(matrix.runs-on, 'ubuntu')
      env:
        SignClientSecret: ${{ secrets.SignClientSecret }}
      run: ./build.ps1 sign

    - name: Push packages to MyGet
      if: github.ref == 'refs/heads/main' && contains(matrix.runs-on, 'ubuntu')
      run: dotnet nuget push artifacts\*.nupkg -s https://www.myget.org/F/duende_identityserver/api/v2/package -k ${{ secrets.MYGET }} --skip-duplicate

    - name: Push NuGet package to GitHub Packages
      if: github.ref == 'refs/heads/main' && contains(matrix.runs-on, 'ubuntu')
      run: dotnet nuget push artifacts\*.nupkg --source https://nuget.pkg.github.com/DuendeSoftware/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main' && contains(matrix.runs-on, 'ubuntu')
      with:
        path: identity-model/artifacts/*.nupkg
        compression-level: 0
        overwrite: true
        retention-days: 15